version: '3.8'

services:
  db:
    image: postgres:alpine
    restart: always
    ports:
      - '5432'
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB_NAME}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U root']
      interval: 60s

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: galkaev

  server:
    image: direcon-junior-db-server
    build: .
    depends_on:
      - db
      - adminer
    ports:
      - 3333:3333
    env_file:
      - .env
    volumes:
      - ./node_modules:/usr/src/app/node_modules:delegated
      - ./start:/usr/src/app/start
      - ./app:/usr/src/app/app
